### ISSUE TITLE
Feature request: check_success to also accept a list of callbacks

### ISSUE THREAD

**Issue by joaonc** [justiniso/polling#24]
Would be great if `check_success` would have the ability to not just receive a callback, but also a list of callbacks.

```
check_success: Union[Callback, List[Callback]]
```

The (very real) use case I have here is that when making a REST call, there are different verifications that need to be made before continuing the code.  These verifications are mix-and-match, depending on the scenario and I would love to do something like:

```
result = polling.poll(
    client.get_data,
    check_success=[
        lambda response: error_check(response, 200),
        validate_data,
        lambda response: check_something_else(response, some_other_args),
    ]
)
```

So `check_success` would only pass if _all_ callables return `True` (if list, otherwise call the one callable passed in `check_success`, as-is now).

**Comment by manvillej** [comment]
I think It would be unclear whether it has to pass all of them or one of them. 

Alternatively, why not just wrap these into a single function? It is simple to create a function that unionizes them all while being more explicit. 

```
check_success = lambda response: all([
    error_check(response,200),
    validate_data(response),
    something_else(response)
])
```

it also allows you do an "any" instead

Alternatively, It is simple to create a function that unionizes them all while being more clear. 

```
check_success = lambda response: any([
    test_1(response),
    test_2(response),
    test_3(response)
])
```

**Comment by joaonc** [comment]
wholy crap, that's an excellent suggestion!  beating myself for not having thought of that before..  Use `any` and `all` all the time.
